[package]
name = "bottles-plugin-api"
description = "Rust guest API for Bottles Next plugins"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1"
http.workspace = true
http-body-util = "0.1"
wasip3 = { version = "0.9", features = ["http-compat"] }
wit-bindgen = "0.62.0"
